### ISSUE TITLE
Startup loop

### ISSUE THREAD

**Issue by gfaivre** [Elao/blogd#5]
BlogD seems fall into a loop when no initial current.json file exists, it finally load data successfully after several iterations.

Debug logs: 

Config: /srv/site/silex/package.json
Backup file var/blog/current.json not found or unreadable
Loading fresh content
Refreshing data from source
Loading posts...
Loading users...
Loading tags...
Checking data...
Data checked status success
Copying assets
Assets from var/blog/content/posts/images/ => web/blog/medias
Copying folders ...
Config: /srv/site/silex/package.json
Backup file var/blog/current.json not found or unreadable
Loading fresh content
Refreshing data from source
Loading posts...
Loading users...
Loading tags...
Checking data...
Data checked status success
Copying assets
Assets from var/blog/content/posts/images/ => web/blog/medias
Copying folders ...
Config: /srv/site/silex/package.json
Backup file var/blog/current.json not found or unreadable
Loading fresh content
Refreshing data from source
Loading posts...
Loading users...
Loading tags...
Checking data...
Data checked status success
Copying assets
Assets from var/blog/content/posts/images/ => web/blog/medias
Copying folders ...
Copying folders succeed
Assets copied
Listening on 127.0.0.1:5555

**Comment by Vincz** [comment]
Fixed in 0.2.4 (see https://github.com/AvianFlu/ncp/issues/66)
